# Generated by Django 4.0.5 on 2022-06-30 20:09

import apps.security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.PositiveIntegerField(db_index=True, default=apps.security.models.get_user_number, null=True, verbose_name='Number'),
        ),
    ]
