# Generated by Django 3.1.2 on 2021-12-01 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20211120_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
            ],
            options={
                'verbose_name': 'workflow',
                'verbose_name_plural': 'work flows',
            },
        ),
    ]
