# Generated by Django 3.1.2 on 2021-12-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_role_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='workflow',
            new_name='workflows',
        ),
    ]
