# Generated by Django 3.1.2 on 2022-01-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_auto_20220107_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification_number',
            field=models.CharField(max_length=50, null=True, verbose_name='identification_number'),
        ),
    ]
