# Generated by Django 3.1.2 on 2022-03-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_user_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telephone'),
        ),
    ]
