# Generated by Django 3.1.2 on 2022-04-01 20:31

import apps.security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_auto_20220325_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='circulation_card',
            field=models.ImageField(help_text='Carnet de circulación', null=True, upload_to=apps.security.models.circulation_card_image_path, verbose_name='circulation card'),
        ),
        migrations.AddField(
            model_name='user',
            name='holder_s_license',
            field=models.ImageField(help_text='Licencia del tomador', null=True, upload_to=apps.security.models.holder_s_license_image_path, verbose_name="holder's license"),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_certificate',
            field=models.ImageField(help_text='Certificado médico', null=True, upload_to=apps.security.models.medical_certificate_image_path, verbose_name='medical certificate'),
        ),
    ]
