# Generated by Django 3.1.2 on 2022-04-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0016_auto_20220401_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification_number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='identification_number'),
        ),
    ]
