# Generated by Django 3.1.2 on 2022-04-07 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0018_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='security.module', verbose_name='module'),
        ),
    ]
