# Generated by Django 3.1.2 on 2022-04-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0021_auto_20220408_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_adviser',
            field=models.BooleanField(default=False, help_text='Define si el usuario es un asesor.', verbose_name='is adviser'),
        ),
    ]
