# Generated by Django 3.1.2 on 2022-06-12 14:37

import apps.security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0022_user_is_adviser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.PositiveIntegerField(db_index=True, default=apps.security.models.get_user_number, null=True, verbose_name='Number'),
        ),
    ]
