# Generated by Django 4.0.5 on 2022-06-30 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='taker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='taker'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.use', verbose_name='use'),
        ),
        migrations.AddField(
            model_name='premium',
            name='coverage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.coverage', verbose_name='coverage'),
        ),
        migrations.AddField(
            model_name='premium',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.plan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='premium',
            name='use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.use', verbose_name='use'),
        ),
        migrations.AddField(
            model_name='policycoverage',
            name='coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.coverage', verbose_name='coverage'),
        ),
        migrations.AddField(
            model_name='policycoverage',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.policy', verbose_name='policy'),
        ),
        migrations.AddField(
            model_name='policy',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_adviser', to=settings.AUTH_USER_MODEL, verbose_name='adviser'),
        ),
        migrations.AddField(
            model_name='policy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_user', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='policy',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.plan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='policy',
            name='taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='taker'),
        ),
        migrations.AddField(
            model_name='policy',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehicle', verbose_name='vehicle'),
        ),
        migrations.AddField(
            model_name='plan',
            name='uses',
            field=models.ManyToManyField(blank=True, to='core.use', verbose_name='uses'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.city', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='model',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mark', verbose_name='mark'),
        ),
        migrations.AddField(
            model_name='coverage',
            name='plans',
            field=models.ManyToManyField(blank=True, to='core.plan', verbose_name='plans'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.state', verbose_name='state'),
        ),
    ]
