# Generated by Django 4.0.5 on 2022-07-20 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('type', models.SmallIntegerField(choices=[(0, 'RCV')], default=0, verbose_name='type')),
                ('change_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='change factor')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.plan', verbose_name='plan')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='taker')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'pre policy',
                'verbose_name_plural': 'pre policies',
            },
        ),
    ]
