# Generated by Django 3.1.2 on 2021-11-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(max_length=255, verbose_name='url'),
        ),
    ]
