# Generated by Django 4.0.5 on 2022-07-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prepolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='link_google_maps',
            field=models.TextField(blank=True, null=True, verbose_name='link google maps'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pendiente de pago'), (1, 'Pendiente de aprobación'), (2, 'Aprobado'), (3, 'Vencido'), (4, 'Pago rechazado')], default=0, verbose_name='status'),
        ),
    ]
