# Generated by Django 4.0.5 on 2022-07-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_branchoffice_link_google_maps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='direction',
            field=models.CharField(max_length=355, null=True, verbose_name='direction'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telephone'),
        ),
    ]
