# Generated by Django 4.0.5 on 2022-07-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_branchoffice_direction_branchoffice_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='direction',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='direction'),
        ),
    ]
