# Generated by Django 4.0.5 on 2022-09-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_branchoffice_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='content',
            field=models.CharField(default='', max_length=255, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(default='', max_length=100, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='url'),
        ),
    ]
