# Generated by Django 3.1.2 on 2022-01-14 16:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='code')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('default', models.BooleanField(default=False, verbose_name='default')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('last_sync_date', models.DateTimeField(blank=True, null=True, verbose_name='last sync date')),
            ],
            options={
                'verbose_name': 'coverage',
                'verbose_name_plural': 'toppings',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('insured_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='price')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='cost')),
                ('last_sync_date', models.DateTimeField(blank=True, null=True, verbose_name='last sync date')),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.coverage', verbose_name='coverage')),
                ('use', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.use', verbose_name='use')),
            ],
            options={
                'verbose_name': 'premium',
                'verbose_name_plural': 'premiums',
            },
        ),
    ]
