# Generated by Django 3.1.2 on 2022-01-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_coverage_premium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coverage',
            options={'ordering': ['code'], 'verbose_name': 'coverage', 'verbose_name_plural': 'coverage'},
        ),
        migrations.AddField(
            model_name='coverage',
            name='plans',
            field=models.ManyToManyField(blank=True, to='core.Plan', verbose_name='plans'),
        ),
    ]
