# Generated by Django 4.0.5 on 2022-11-18 23:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_section_content_alter_section_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='amount')),
                ('detail', models.TextField(verbose_name='detail')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidences', to='core.policy', verbose_name='policy')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidences', to='core.vehicle', verbose_name='vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
