# Generated by Django 3.1.2 on 2022-01-14 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220114_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.plan', verbose_name='plan'),
        ),
    ]
