# Generated by Django 3.1.2 on 2022-02-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mark_model_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
