# Generated by Django 3.1.2 on 2022-02-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mark_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
