# Generated by Django 3.1.2 on 2022-02-10 14:29

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_model_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_data',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='circulation_card',
            field=models.ImageField(help_text='Carnet de circulación', null=True, upload_to=apps.core.models.circulation_card_image_path, verbose_name='circulation card'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='holder_s_license',
            field=models.ImageField(help_text='Licencia del tomador', null=True, upload_to=apps.core.models.holder_s_license_image_path, verbose_name="holder's license"),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='medical_certificate',
            field=models.ImageField(help_text='Certificado médico', null=True, upload_to=apps.core.models.medical_certificate_image_path, verbose_name='medical certificate'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_identity_card',
            field=models.ImageField(help_text='Cédula de identidad del dueño', null=True, upload_to=apps.core.models.owner_identity_card_image_path, verbose_name='owner identity card'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_last_name',
            field=models.CharField(blank=True, help_text='Apellido del dueño', max_length=100, null=True, verbose_name='owner lastname'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_license',
            field=models.ImageField(help_text='Licencia del dueño', null=True, upload_to=apps.core.models.owner_license_image_path, verbose_name='owner license'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_medical_certificate',
            field=models.ImageField(help_text='Certificado médico del dueño', null=True, upload_to=apps.core.models.owner_medical_certificate_image_path, verbose_name='owner medical certificate'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Nombre del dueño', max_length=100, null=True, verbose_name='owner name'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_rif',
            field=models.ImageField(help_text='RIF del dueño', null=True, upload_to=apps.core.models.owner_rif_image_path, verbose_name='owner_rif'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_certificate',
            field=models.ImageField(help_text='Certificado de registro de vehículo (Tiutlo)', null=True, upload_to=apps.core.models.registration_certificate_image_path, verbose_name='registration certificate'),
        ),
    ]
