# Generated by Django 3.1.2 on 2022-02-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220210_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='link_google_maps',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='link google maps'),
        ),
    ]
