# Generated by Django 3.1.2 on 2022-02-10 18:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_location_link_google_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='link_google_maps',
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='geo location'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='link_google_maps',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='link google maps'),
        ),
    ]
