# Generated by Django 3.1.2 on 2022-03-28 02:43

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_auto_20220324_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('number', models.PositiveIntegerField(db_index=True, default=apps.core.models.get_policy_number, verbose_name='number')),
                ('type', models.SmallIntegerField(choices=[(0, 'RCV')], default=0, verbose_name='type')),
                ('action', models.SmallIntegerField(choices=[(0, 'Nueva')], default=0, verbose_name='action')),
                ('due_date', models.DateTimeField(help_text='Fecha de vencimiento', verbose_name='due_date')),
                ('status', models.SmallIntegerField(choices=[(0, 'pendiente de pago'), (1, 'pendiente de aprobación'), (2, 'aprobado'), (3, 'vencido'), (4, 'rechazado')], default=0, verbose_name='status')),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_adviser', to=settings.AUTH_USER_MODEL, verbose_name='adviser')),
                ('insured', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_insured', to=settings.AUTH_USER_MODEL, verbose_name='insured')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='taker')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'policy',
                'verbose_name_plural': 'policies',
            },
        ),
        migrations.CreateModel(
            name='PolicyCoverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('number', models.PositiveIntegerField(db_index=True, default=apps.core.models.get_policy_coverage_number, verbose_name='number')),
                ('insured_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='price')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='cost')),
                ('change_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='change factor')),
                ('coverage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.coverage', verbose_name='coverage')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.policy', verbose_name='policy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
