# Generated by Django 3.1.2 on 2022-04-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_policy_policycoverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='circulation_card',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='holder_s_license',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='medical_certificate',
        ),
    ]
