# Generated by Django 3.1.2 on 2022-04-01 20:35

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220401_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner_identity_card_image',
            field=models.ImageField(help_text='Cédula de identidad del dueño Imagen', null=True, upload_to=apps.core.models.owner_identity_card_image_path, verbose_name='owner identity card'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_rif_image',
            field=models.ImageField(help_text='RIF del dueño Imagen', null=True, upload_to=apps.core.models.owner_rif_image_path, verbose_name='owner_rif'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner_identity_card',
            field=models.CharField(blank=True, help_text='Cedula del dueño', max_length=100, null=True, verbose_name='owner_identity_card'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner_rif',
            field=models.CharField(blank=True, help_text='Rif del dueño', max_length=100, null=True, verbose_name='owner_identity_card'),
        ),
    ]
