# Generated by Django 3.1.2 on 2022-04-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220401_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner_address',
            field=models.CharField(blank=True, help_text='Dirección del dueño', max_length=100, null=True, verbose_name='owner address'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Correo del dueño', max_length=100, null=True, verbose_name='owner email'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_phones',
            field=models.CharField(blank=True, help_text='Telefonos del dueño', max_length=100, null=True, verbose_name='owner phones'),
        ),
    ]
