# Generated by Django 3.1.2 on 2022-04-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20220401_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='code',
        ),
        migrations.RemoveField(
            model_name='model',
            name='code',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='insured',
        ),
        migrations.AlterField(
            model_name='mark',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True, verbose_name='description'),
        ),
    ]
