# Generated by Django 3.1.2 on 2022-04-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20220405_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
