# Generated by Django 3.1.2 on 2022-04-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_vehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.plan', verbose_name='plan'),
        ),
    ]
