# Generated by Django 3.1.2 on 2022-04-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_policy_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='due_date',
            field=models.DateTimeField(help_text='Fecha de vencimiento', null=True, verbose_name='due_date'),
        ),
    ]
