# Generated by Django 3.1.2 on 2022-04-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_historicalchangerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_certificate',
        ),
    ]
