# Generated by Django 3.1.2 on 2022-04-05 21:22

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_vehicle_registration_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner_circulation_card',
            field=models.ImageField(help_text='Carnet de circulación del dueño', null=True, upload_to=apps.core.models.owner_circulation_card_image_path, verbose_name='owner circulation card'),
        ),
    ]
