# Generated by Django 3.1.2 on 2022-04-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20220405_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='total'),
        ),
        migrations.AddField(
            model_name='policy',
            name='total_change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='total change'),
        ),
    ]
