# Generated by Django 3.1.2 on 2022-04-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220406_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='total_change',
        ),
        migrations.RemoveField(
            model_name='policycoverage',
            name='change_factor',
        ),
        migrations.AddField(
            model_name='policy',
            name='change_factor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='change factor'),
        ),
    ]
