# Generated by Django 3.1.2 on 2022-04-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20220406_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='policy',
            name='total_insured_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='total'),
        ),
    ]
