# Generated by Django 3.1.2 on 2022-04-10 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0035_auto_20220406_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='taker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='taker'),
        ),
    ]
