# Generated by Django 3.1.2 on 2022-04-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20220410_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='serial_bodywork',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='serial bodywork'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='serial_engine',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='serial engine'),
        ),
    ]
