# Generated by Django 3.1.2 on 2022-04-14 12:13

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20220411_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.core.models.banner_image_path, verbose_name='image'),
        ),
    ]
