# Generated by Django 3.1.2 on 2022-04-16 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20220414_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policycoverage',
            options={'ordering': ['number'], 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
    ]
