# Generated by Django 3.1.2 on 2022-04-17 20:06

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_policy_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-number'], 'verbose_name': 'policy', 'verbose_name_plural': 'policies'},
        ),
        migrations.AddField(
            model_name='policy',
            name='qrcode',
            field=models.ImageField(null=True, upload_to=apps.core.models.qrcode_image_path, verbose_name='qrcode image'),
        ),
    ]
