# Generated by Django 3.1.2 on 2022-04-17 20:24

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20220417_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='file',
            field=models.FileField(null=True, upload_to=apps.core.models.file_policy_path, verbose_name='file policy pdf'),
        ),
    ]
