# Generated by Django 3.1.2 on 2022-06-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20220602_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchoffice',
            name='last_sync_date',
        ),
    ]
