# Generated by Django 3.1.2 on 2022-06-11 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_use_last_sync_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverage',
            name='last_sync_date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='last_sync_date',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='last_sync_date',
        ),
    ]
