# Generated by Django 3.1.2 on 2022-06-13 15:46

import apps.core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20220611_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('type', models.CharField(choices=[('box', 'Caja'), ('about', 'Sobre'), ('service', 'Servicio'), ('partner', 'Asociado')], default='box', max_length=10, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(max_length=100, verbose_name='subtitle')),
                ('content', models.CharField(max_length=300, verbose_name='content')),
                ('image', models.ImageField(null=True, upload_to=apps.core.models.section_image_path, verbose_name='image')),
                ('shape', models.ImageField(null=True, upload_to=apps.core.models.section_shape_path, verbose_name='shape')),
                ('icon', models.ImageField(null=True, upload_to=apps.core.models.section_icon_path, verbose_name='icon')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('sequence_order', models.IntegerField(default=1, verbose_name='sequence order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ['sequence_order'],
            },
        ),
    ]
