# Generated by Django 3.1.2 on 2022-06-01 14:29

import apps.payment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0042_policy_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='code')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('image', models.ImageField(null=True, upload_to=apps.payment.models.bank_archive_path, verbose_name='image')),
                ('status', models.SmallIntegerField(choices=[(1, 'activo'), (0, 'inactivo')], default=1, verbose_name='status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('number', models.PositiveIntegerField(db_index=True, default=apps.payment.models.get_payment_number, verbose_name='Number')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('igtf_amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('commentary', models.CharField(blank=True, max_length=255, null=True, verbose_name='commentary')),
                ('method', models.SmallIntegerField(choices=[(0, 'Transferencia'), (1, 'Pago móvil'), (2, 'Efectivo'), (3, 'Zelle'), (4, 'Otro')], default=0, verbose_name='status')),
                ('coin', models.CharField(default='USD', max_length=255, verbose_name='coin')),
                ('archive', models.FileField(null=True, upload_to=apps.payment.models.payment_archive_path, verbose_name='archive')),
                ('change_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='change factor')),
                ('status', models.SmallIntegerField(choices=[(0, 'pendiente'), (1, 'rechazado'), (2, 'aceptado')], default=0, verbose_name='status')),
                ('igtf', models.BooleanField(blank=True, default=False, null=True)),
                ('percentage_igtf', models.IntegerField(blank=True, default=3, null=True)),
                ('reference_igtf', models.CharField(help_text='Código de referencia de pago de igtf por separado.', max_length=255, null=True, verbose_name='reference igtf')),
                ('archive_igtf', models.FileField(null=True, upload_to=apps.payment.models.payment_archive_igtf_path, verbose_name='archive igtf')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='payment date')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.bank', verbose_name='bank')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.policy', verbose_name='order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_payments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
