# Generated by Django 3.1.2 on 2022-06-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='archive_igtf',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='igtf',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='igtf_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='percentage_igtf',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference_igtf',
        ),
    ]
