# Generated by Django 3.1.2 on 2022-06-02 16:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20220602_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='account_name'),
        ),
        migrations.AddField(
            model_name='bank',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='account_number'),
        ),
        migrations.AddField(
            model_name='bank',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='bank',
            name='methods',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Transferencia'), (1, 'Pago móvil'), (2, 'Efectivo'), (3, 'Zelle'), (4, 'Otro')], default=None, max_length=9, verbose_name='methods'),
        ),
    ]
